<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HSEBank.Entities\HSEBank.Entities.csproj" />
      <ProjectReference Include="..\HSEBank.UseCases\HSEBank.UseCases.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
      <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

</Project>
